src/api/cafes.ts, src/interfaces/ICafe.ts, src/models/Cafe.ts, src/models/Review.ts, src/services/cafeService.ts
```
```
해당 pr에서 작업한 내역을 적어주세요.
cafe controller, service 코드를 작성했습니다.
close #7
=> Feature/#7 CAFE API 코드 작성

src/api/cafes.ts, src/modules/responseMessage.ts, src/services/cafeService.ts
```
```
해당 pr에서 작업한 내역을 적어주세요.
responseMessage에 NO_CONTENT, INVALID_IDENTIFIER가 추가되었습니다.
close #11
=> Feature/#11 CAFE datil api 작성

package.json, src/index.ts
- http-errors 추가
- Index.ts error handler 수정
- index.ts 서버 포트 '5000' 상수에서 config 포트 값으로 변경
모듈이 추가되어 yarn install 해야함
close #17
=> Feature/#17 http-errors 모듈 추가, error handler 수정

src/modules/dateCalculate.ts
```
```
db에 저장되는 date time 기준을 utc+0900으로 맞추기 위한 모듈 생성 
- modules/dateCalculate.ts
close #20
=> [feat] db에 저장되는 date time 기준을 utc+0900으로 맞추기 위한 모듈 생성

src/api/cafeti.ts, src/api/category.ts, src/api/user.ts, src/index.ts, src/interfaces/ICafeti.ts, src/interfaces/IUser.ts, src/models/User.ts, src/services/cafetiService.ts, src/services/categoryService.ts, src/services/userService.ts
```
```
CAFETI API 신규 코드 작성, SignUp created_at time zone 변경
- services/cafetiService.ts
- services/userService.ts
- api/cafeti.ts
close #19
=> Feature/#19 CAFETI API 신규 코드 작성

src/api/cafes.ts, src/api/reviews.ts, src/services/cafeService.ts, src/services/categoryService.ts, src/services/reviewService.ts
- cafe detail -> isSaved 추가
- cafe review -> average(별점) 추가, 날짜 역순 정렬 추가
- category service -> checkCafeInCategory (핀 여부)
close #15
=> Feature/#15 CAFE API isSaved, REVIEW API 평균 별점 추가

src/api/reviews.ts, src/api/user.ts, src/services/reviewService.ts
- 내 리뷰 가져오는 service, controller 생성
close #26
=> [feat] 내 리뷰 조회 추가

src/api/cafes.ts, src/models/Cafe.ts, src/services/reviewService.ts
get cafe detail 에서 그 카페에 대한 별점이 없는 경우 average 필드를 보내지 않음
- 별점 없는 카페 에러 처리
- Cafe model offday default : undefined 처리
- Cafe model rating 필드 삭제
close #28
=> [fix] 별점 없는 카페 에러 처리

src/api/user.ts, src/modules/responseMessage.ts, src/services/categoryService.ts, src/services/userService.ts
```
```
- 유저 정보 조회 API 신규 작성
- 카테고리 속 카페 리스트 보기 API responseBody 수정
close #23
=> Feature/#23 유저 정보 조회 API 신규 작성 및 카테고리 속 카페 리스트 보기 API 수정

src/middleware/auth.ts, src/modules/responseMessage.ts
auth 미들웨어의 토큰 관련 응답값을 수정했습니다.
close #31
=> Feature/#31 토큰 에러 응답 메세지 변경

src/models/Cafe.ts, src/models/Cafeti.ts, src/models/Category.ts, src/models/CategoryColor.ts, src/models/Review.ts, src/models/Tag.ts, src/models/User.ts
-모든 모델 스키마에 versionKey:false 추가
close #34
=> [fix] 모든 모델 스키마에 versionKey:false 추가

package.json, src/api/geocoder.ts, src/config/index.ts, src/index.ts, src/models/Cafe.ts, src/services/cafeService.ts, src/services/geocoderService.ts
- geocoder API 추가
- 1. 카페 데이터 중 좌표가 없는 데이터들 일괄적으로 좌표 변환
- 2. 특정 카페id로 좌표 변환
- axios 모듈이 추가되었습니다.
yarn install 해주세요
- .env 내용이 변경되었습니다.
close #39
=> Feature/#39 Naver Geocoding API 추가

src/api/reviews.ts, src/interfaces/ICafe.ts, src/interfaces/IReview.ts, src/models/Review.ts, src/services/cafeService.ts, src/services/reviewService.ts
- 빈 필드는 빈 배열이 아니라 아예 값이 없게 수정
- getMyReview, getCafeReview에서 불필요한 필드를 제거하고 이름 수정
close #41
=> Feature/#41 getMyReview, getCafeReview 응답값 수정

src/api/cafeti.ts, src/api/category.ts, src/api/user.ts
```
```
_id, idx값 받아야 하는 api에서 path parameter로 받기 통일, 코드 스타일 점검
close #45
=> Feature/#45 _id, idx값 받아야 하는 api에서 path parameter로 받기 통일, 코드 스타일 점검

package.json, src/api/user.ts, src/modules/responseMessage.ts, src/services/userService.ts
```
```
- 이메일 인증 API 개발
- 새 비밀번호 API 개발
- 이메일 인증 때문에 nodemailer 설치하였습니다. **yarn install 해주세요!**
- .env파일도 변경되었습니다 슬랙으루 공유드릴게요
close #47
=> Feature/#47 비밀번호 찾기 API 개발

src/api/category.ts, src/models/CategoryColor.ts, src/modules/responseMessage.ts, src/services/categoryService.ts
```
```
- 카테고리 수정 API
- 카테고리 내 카페 삭제 API
close #48
=> Feature/#48 카테고리 수정 및 카테고리 내 카페 삭제 API 구현

src/interfaces/ICafeti.ts, src/models/Cafeti.ts, src/models/User.ts
```
```
cafeti responseBody 변경, cafeti 모델 수정
- cafeti api responseBody 변경
- cafeti 모델 수정
close #53
=> [feat] edit cafeti interface, model

src/api/cafes.ts, src/interfaces/IMenu.ts, src/loader/db.ts, src/models/Menu.ts, src/modules/responseMessage.ts, src/services/menuService.ts
- Menu interface, model
- getCafeMenuService
- cafe api에 ~cafes/:cafeId/menus 추가
close #50
=> Feature/#50 getCafeMenuList 구현

src/api/cafes.ts
기존 cafes?tags={1,2}에서
cafes?tags=1&tags=2로 변경
close #58
=> [fix] getCafeLocation changes query type

src/api/cafes.ts
- getCafeLocation controller tag 없는 경우 빈 배열 전달
close #61
=> [fix] getCafeLocation contoller tag 없는 경우 빈 배열 전달

src/api/admin.ts, src/api/geocoder.ts, src/api/reviews.ts, src/config/index.ts, src/index.ts, src/services/cafeService.ts
해당 pr에서 작업한 내역을 적어주세요.
- cafeId로 이미지 업로드 하는 API 추가 (관리자only)
- geocoder를 admin controller로 옮기고 adminKey 확인 추가
close #67
=> Feature/#67 카페 이미지 업로드 API

src/api/search.ts, src/index.ts, src/interfaces/ICafe.ts, src/modules/responseMessage.ts, src/services/cafeService.ts
```
```
카페명으로 검색해서 검색어로 시작하는 결과 리턴
close #70
=> Feature/#70 카페명으로 카페 검색 API 작성

src/api/reviews.ts, src/middleware/upload.ts, src/modules/responseMessage.ts
```
```
REVIEW API - recommend 있을 때 에러 처리 안됐던 버그 수정
close #73
=> Feature/#73 REVIEW post, put 에서 recommend 있을 때 에러 처리 안됐던 버그 수정

src/services/userService.ts
```
```
유저 정보 가져오기 API에서 리뷰 갯수 관련 코드를 수정하였습니다.
close #81
=> [fix] fetch userInfo API bug fixed

src/services/categoryService.ts
```
```
카테고리 내 카페 리스트 조회 API 개선
close #83
=> [refactor] 카테고리 내 카페 리스트 조회 API 개선
